# Generated by Django 4.2.1 on 2023-05-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=70, null=True)),
                ('market_name', models.CharField(max_length=100, null=True)),
                ('cawarock', models.CharField(max_length=100, null=True)),
                ('category', models.IntegerField(null=True)),
                ('floor', models.CharField(max_length=20, null=True)),
                ('open_check', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('keyword_common', models.CharField(max_length=1000, null=True)),
                ('keyword_detail', models.CharField(max_length=1000, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('open_hours', models.CharField(max_length=1000, null=True)),
                ('item', models.CharField(max_length=1000, null=True)),
                ('explain', models.CharField(max_length=2000, null=True)),
                ('section', models.CharField(max_length=70, null=True)),
                ('review', models.JSONField(max_length=1000, null=True)),
                ('grade', models.JSONField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yeouijus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeouijus', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='picklist',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_img',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='reivew',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='step',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='yeouijus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
