# Generated by Django 4.0.3 on 2023-05-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_market_db_yeouijus_account_age_account_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market_db',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='market_db',
            name='img',
        ),
        migrations.RemoveField(
            model_name='market_db',
            name='review',
        ),
        migrations.AlterField(
            model_name='market_db',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='cawarock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='explain',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='keyword_common',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='keyword_detail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='lot_number',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='market_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='open_check',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='open_hours',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='market_db',
            name='section',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='reivew contents')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.account')),
                ('market', models.ForeignKey(db_column='market', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.market_db')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('market', models.ForeignKey(db_column='market', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='app.market_db')),
            ],
        ),
    ]
