# Generated by Django 4.0.3 on 2023-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_market_db_grade_remove_market_db_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='reivew',
        ),
        migrations.RemoveField(
            model_name='account',
            name='yeouijus',
        ),
        migrations.AddField(
            model_name='account',
            name='review',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='picklist',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='point',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='step',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
