# Generated by Django 4.0.3 on 2023-06-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_account_reivew_remove_account_yeouijus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='review',
            name='market',
        ),
        migrations.AddField(
            model_name='review',
            name='market_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite6', to='app.market_db'),
        ),
        migrations.AlterField(
            model_name='review',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite5', to='app.account'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite', to='app.account')),
                ('agerange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite3', to='app.account')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite4', to='app.account')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite2', to='app.market_db')),
            ],
        ),
    ]
