# Generated by Django 4.0.3 on 2023-06-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_review_grade_remove_review_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_db',
            name='find_number',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
