# Generated by Django 4.0.3 on 2023-06-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_market_db_find_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
