# Generated by Django 4.0.3 on 2023-06-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_review_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '유저 정보'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': '찜목록'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': '가게 이미지'},
        ),
        migrations.AlterModelOptions(
            name='market_db',
            options={'verbose_name_plural': '가게 정보'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': '리뷰'},
        ),
    ]
