# Generated by Django 4.0.3 on 2023-06-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_account_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.account')),
                ('profile_img', models.IntegerField(default=None, null=True)),
                ('nickname', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
    ]
