# Generated by Django 4.0.3 on 2023-08-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_db',
            name='latitude',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='market_db',
            name='longitude',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
